# Generated by Django 2.1.3 on 2018-12-10 23:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDoc', models.CharField(max_length=100)),
                ('fechaSubida', models.DateField(auto_now=True)),
                ('imagenDoc', models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('fechaLimite', models.DateField()),
                ('documento', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['docx', 'pdf'])])),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmado', models.BooleanField()),
                ('idDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documentos.Documento')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repositorio',
                'verbose_name_plural': 'Repositorios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_perfil', models.ImageField(default='', upload_to='imagenesPerfil', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='idRepositorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documentos.Repositorio'),
        ),
    ]
