# Generated by Django 2.1.3 on 2018-12-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='certificado',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
