# Generated by Django 2.1.3 on 2018-12-15 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.FileField(upload_to='documentos', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
