# Generated by Django 2.1.3 on 2018-12-14 05:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=100)),
                ('idUsuarioDestinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to=settings.AUTH_USER_MODEL)),
                ('idUsuarioRemitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.RemoveField(
            model_name='repositorio',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='idRepositorio',
        ),
        migrations.AddField(
            model_name='documento',
            name='imagen_documento',
            field=models.ImageField(default='', upload_to='imagenesDocumento', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
        migrations.AddField(
            model_name='permiso',
            name='esPropietario',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Repositorio',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='idDocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documentos.Documento'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
