# Generated by Django 2.1.3 on 2018-11-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen_perfil',
        ),
    ]
