# Generated by Django 2.1.3 on 2018-12-10 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='imagenDoc',
        ),
    ]
