# Generated by Django 2.1.2 on 2018-12-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0002_auto_20181215_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
