# Generated by Django 2.1.3 on 2018-11-29 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0002_remove_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(default='', upload_to='imagenesPerfil/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
