# Generated by Django 2.1.3 on 2018-12-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0002_remove_documento_imagendoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fechaSubida',
            field=models.DateField(auto_now_add=True),
        ),
    ]
