# Generated by Django 2.1.2 on 2018-11-29 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0003_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(default='', upload_to='imagenesPerfil', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])]),
        ),
    ]
