# Generated by Django 2.1.2 on 2018-12-16 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0003_notificacion_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='idMensaje',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Documentos.Chat'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='idDocumento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Documentos.Documento'),
        ),
    ]
